export const CHAMADAS_LIST = [
  "A Estrela Que Aqui Clareia",
  "A Estrela Vem Brilhando",
  "A Lua Vem Surgindo",
  "A Luz Que Me Guia",
  "Abalei a Terra",
  "Abalo da Consciência",
  "Água da Vida",
  "Amigo",
  "Amigo do Peito",
  "Amor de Mãe",
  "Amor de Nós",
  "Amor Vivíssimo",
  "Amparo",
  "Ancarilho",
  "Anjo da Minha Guarda",
  "Arvoredo",
  "Astral Resplandecente",
  "Autor do Conselho",
  "Barquinha",
  "Batismo Perfeito",
  "Bem-Te-Vi",
  "Caiano",
  "Cajueiro",
  "Cajueiro Pequenino",
  "Caminho Claro",
  "Caminho de Um",
  "Caminho do Mestre",
  "Caminho Firme",
  "Canário",
  "Canto da Sereia",
  "Casal Perfeito",
  "Castelo da Ciência",
  "Castelo Universal",
  "Catorze Anjos Divinos",
  "Com Deus Firme Sempre Estou",
  "Confirmação",
  "Conformação",
  "Conselho",
  "Convite aos Encantos",
  "Coração do Mestre",
  "Coração Fiel",
  "Cores do Uniforme",
  "Correger Terra",
  "Correição do Coração",
  "Correição pela Vaidade",
  "Correr pra Onde Tem Sombra",
  "Crescendo Devagarinho",
  "Da Palavra do Senhor",
  "Despedida da Guarnição",
  "Digo Graças a Deus",
  "Divino Salvador",
  "Do Tombo",
  "Doutor Camalango",
  "Estrela Brilhante",
  "Estrela D'Alva",
  "Estrela Divina",
  "Estrela do Norte",
  "Estrela do Oriente",
  "Estrela Guia",
  "Estrondou na Barra",
  "Exame e Correição do Mestre Equilibrando",
  "Expansão",
  "Firmeza e Compreensão",
  "Força da Natureza",
  "Força do Amor",
  "Força do Mestre Gabriel",
  "Fortaleza do Mestre",
  "Fortuna",
  "Funil",
  "Galo",
  "Gaspar",
  "Geração da Arca de Noé",
  "Globo",
  "Graças a Deus",
  "Grande Esperança",
  "Grande Foco",
  "Grande Ventura",
  "Guarnição Divina",
  "Hoasca",
  "Jardim das Flores",
  "Jardim do Chacronal",
  "Jardim do Norte",
  "Jardim Florido",
  "Jardim Real",
  "Jesus Veio Ao Mundo",
  "Justiça Divina",
  "Justiça do Mestre Gabriel",
  "Justiça do Vegetal",
  "Ladeira dos Caianinhos",
  "Lago de Burracheira",
  "Linha de Tucunacá",
  "Lua",
  "Lupunamanta",
  "Luz do Chacronal",
  "Luz Sublime",
  "Mãe Gloriosa",
  "Manué Messias",
  "Mariri Florando",
  "Menino Deus",
  "Mestre dos Mestres é Deus",
  "Meu Bom Jesus",
  "Meu Divino São João",
  "Meu Jesus Crucificado",
  "Minguarana",
  "Minha Firmeza",
  "Mistérios de Deus",
  "Mistérios do Vegetal",
  "Nascimento de Jesus",
  "Nascimento de Mestre Gabriel",
  "No Azul do Mar",
  "No Início da União",
  "No Princípio é Deus",
  "Nove Vegetal",
  "Nuvem Clara e Pura",
  "O Homem na Missão",
  "Outeiro Alto",
  "Pai da Geração",
  "Passarinhos",
  "Peleja",
  "Peneira",
  "Perambulando Até Chegar",
  "Perdi Pai Perdi Mãe",
  "Piaba",
  "Ponto da Meia Noite",
  "Pra Deus Nada é Impossível",
  "Princesa Mariana",
  "Quando Adão Aqui na Terra",
  "Quando Eu Quero Dou Um Nó",
  "Quando o Mariri Florou",
  "Rainha das Águas",
  "Rei Canaã",
  "Rei dos Chefes",
  "Rei Inca e Hoasca",
  "Rei Rabino",
  "Ronda",
  "Sabiá",
  "Sagrada União",
  "Sagrado Poder",
  "Samaúma",
  "São Cosmo e São Damião",
  "Senhora das Águas",
  "Senhora Santana",
  "Serenita",
  "Silêncio",
  "Símbolo da União",
  "Socorro Divino",
  "Sol",
  "Solhinha",
  "Sombreia",
  "Sonho",
  "Sou Mariri Sou Chacrona",
  "Supairunã",
  "Tempo",
  "Tenha Piedade",
  "Tesourinha de Bom Corte",
  "Tiuaco",
  "Tiuaco é Mariri",
  "Todo o Cipó",
  "Três Reis",
  "Três Reis Magos",
  "Um Belo Jardim",
  "Um Vem Vem",
  "União",
  "União das Barquinhas",
  "Vem ó Mestre Gabriel",
  "Vento Divino",
  "Virgem Maria",
  "Vitória",
] as const;

export type Chamada = typeof CHAMADAS_LIST[number];
