-- Persist application failures without exposing the log table to client-side
-- mutation. Timestamps are generated by the database for consistency.
CREATE TABLE public.error_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  error_message text NOT NULL,
  error_location text NOT NULL,
  operation text,
  entity text,
  entity_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT error_logs_message_not_empty
    CHECK (length(btrim(error_message)) > 0),
  CONSTRAINT error_logs_location_not_empty
    CHECK (length(btrim(error_location)) > 0),
  CONSTRAINT error_logs_metadata_is_object
    CHECK (jsonb_typeof(metadata) = 'object')
);

COMMENT ON TABLE public.error_logs IS
  'Falhas técnicas registradas pelo cliente da aplicação.';
COMMENT ON COLUMN public.error_logs.error_location IS
  'Ponto lógico da aplicação onde a falha ocorreu.';
COMMENT ON COLUMN public.error_logs.occurred_at IS
  'Horário da falha, definido pelo servidor do banco.';

ALTER TABLE public.error_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Editors can read error logs"
  ON public.error_logs
  FOR SELECT
  TO authenticated
  USING (public.has_role(auth.uid(), 'editor'::public.app_role));

-- Logs are append-only from the application. Inserts happen exclusively
-- through the constrained SECURITY DEFINER function below.
REVOKE ALL ON TABLE public.error_logs FROM anon, authenticated;
GRANT SELECT ON TABLE public.error_logs TO authenticated;

CREATE OR REPLACE FUNCTION public.log_application_error(
  p_error_message text,
  p_error_location text,
  p_operation text DEFAULT NULL,
  p_entity text DEFAULT NULL,
  p_entity_id text DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_log_id uuid;
  v_metadata jsonb;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Autenticação necessária para registrar um erro'
      USING ERRCODE = '42501';
  END IF;

  IF COALESCE(btrim(p_error_message), '') = ''
    OR COALESCE(btrim(p_error_location), '') = '' THEN
    RAISE EXCEPTION 'Mensagem e local do erro são obrigatórios'
      USING ERRCODE = '22023';
  END IF;

  v_metadata := CASE
    WHEN jsonb_typeof(COALESCE(p_metadata, '{}'::jsonb)) = 'object'
      THEN COALESCE(p_metadata, '{}'::jsonb)
    ELSE '{}'::jsonb
  END;

  IF octet_length(v_metadata::text) > 8192 THEN
    v_metadata := jsonb_build_object('metadata_truncated', true);
  END IF;

  INSERT INTO public.error_logs (
    error_message,
    error_location,
    operation,
    entity,
    entity_id,
    metadata,
    user_id
  )
  VALUES (
    left(p_error_message, 4000),
    left(p_error_location, 200),
    left(p_operation, 30),
    left(p_entity, 100),
    left(p_entity_id, 200),
    v_metadata,
    auth.uid()
  )
  RETURNING id INTO v_log_id;

  RETURN v_log_id;
END;
$$;

REVOKE ALL ON FUNCTION public.log_application_error(text, text, text, text, text, jsonb)
  FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_application_error(text, text, text, text, text, jsonb)
  TO authenticated;

CREATE INDEX error_logs_occurred_at_idx
  ON public.error_logs (occurred_at DESC);
CREATE INDEX error_logs_location_occurred_at_idx
  ON public.error_logs (error_location, occurred_at DESC);
